apiVersion: v1
kind: List
metadata:
  name: azuredisk-csi-driver-sc
  namespace: kube-system
  annotations:
    version: 1.3.0
items:
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azuredisk-gold
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.3.0
    provisioner: disk.csi.azure.com
    parameters:
      skuname: Premium_LRS
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
