apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sat-azure-block-gold
  labels:
    app.kubernetes.io/name: azuredisk-csi-driver
    app.kubernetes.io/version: 1.3.0
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
