apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ name }}"
  annotations:
  storageclass.kubernetes.io/is-default-class: "{{ is-default-class }}"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  selector: "{{ selector }}"
