apiVersion: v1
kind: List
metadata:
  name: armada-storage-s3fs-plugin
  namespace: "{{ namespace }}"
  annotations:
    version: "{{ chart_version }}"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: cos-plugin-installer-sa
      namespace: "{{ namespace }}"
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: cos-plugin-installer
      namespace: "{{ namespace }}"
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "update", "create", "delete"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["list", "watch", "create", "update"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: [""]
        resources: ["configmaps"]
        resourceNames: ["cluster-info"]
        verbs: ["get"]
      - apiGroups: [""]
        resources: ["nodes", "services"]
        verbs: ["get", "list"]
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "create", "delete"]
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "create", "list", "update"]
      - apiGroups: [""]
        resources: ["serviceaccounts"]
        verbs: ["get", "create"]
      - apiGroups: ["apps"]
        resources: ["daemonsets", "deployments"]
        verbs: ["get", "create"]
      - apiGroups: ["security.openshift.io"]
        resources: ["securitycontextconstraints"]
        verbs: ["get", "create"]
      - apiGroups: ["rbac.authorization.k8s.io"]
        resources: ["clusterroles", "clusterrolebindings"]
        verbs: ["get", "create"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: cos-plugin-installer
      namespace: "{{ namespace }}"
    subjects:
      - kind: ServiceAccount
        name: cos-plugin-installer-sa
        namespace: "{{ namespace }}"
    roleRef:
      kind: ClusterRole
      name: cos-plugin-installer
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: v1
    kind: Pod
    metadata:
      name: cos-plugin-installer-pod
      namespace: "{{ namespace }}"
    spec:
      serviceAccountName: cos-plugin-installer-sa
      restartPolicy: Never
      containers:
        - name: cos-plugin-installer
          image: bhagyak1/cos-installer:v01
          env:
            - name: HELM_REPO_NAME
              value: "{{ helm_repo }}"
            - name: HELM_REPO_URL
              value: "{{{ helm_repo_url }}}"
            - name: SAT_NAMESPACE
              value: "{{ namespace }}"
            - name: SAT_CHART_VERSION
              value: "{{ chart_version }}"
            - name: SAT_CHART_NAME
              value: "ibm-object-storage-plugin"
            - name: HELM_OPTIONS
              value: "license={{ license }},provider={{ provider }},workerOS={{ workerOS }},kubeDriver={{{ kubeDriver }}},cpu={{ cpu }},memory={{ memory }}"

