apiVersion: v1
kind: List
metadata:
  name: armada-storage-s3fs-plugin
  namespace: "{{ namespace }}"
  annotations:
    version: "2.0.6"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: cos-plugin-installer-sa
      namespace: "{{ namespace }}"
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: cos-plugin-installer
      namespace: "{{ namespace }}"
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "update", "create", "delete"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["list", "watch", "create", "update"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: [""]
        resources: ["configmaps"]
        resourceNames: ["cluster-info"]
        verbs: ["get"]
      - apiGroups: [""]
        resources: ["nodes", "services"]
        verbs: ["get", "list"]
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "create", "delete"]
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "create", "list", "update"]
      - apiGroups: [""]
        resources: ["serviceaccounts"]
        verbs: ["get", "create"]
      - apiGroups: ["apps"]
        resources: ["daemonsets", "deployments"]
        verbs: ["get", "create"]
      - apiGroups: ["security.openshift.io"]
        resources: ["securitycontextconstraints"]
        verbs: ["get", "create"]
      - apiGroups: ["rbac.authorization.k8s.io"]
        resources: ["clusterroles", "clusterrolebindings"]
        verbs: ["get", "create"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: cos-plugin-installer
      namespace: "{{ namespace }}"
    subjects:
      - kind: ServiceAccount
        name: cos-plugin-installer-sa
        namespace: "{{ namespace }}"
    roleRef:
      kind: ClusterRole
      name: cos-plugin-installer
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: v1
    kind: Pod
    metadata:
      name: cos-plugin-installer-pod
      namespace: "{{ namespace }}"
    spec:
      serviceAccountName: cos-plugin-installer-sa
      restartPolicy: Never
      containers:
        - name: cos-plugin-installer
          image: bhagyak1/cos-installer:v04
          env:
            - name: HELM_REPO_NAME
              value: "ibm-helm"
            - name: HELM_REPO_URL
              value: "https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm"
            - name: SAT_CHART_VERSION
              value: "2.0.6"
            - name: SAT_CHART_NAME
              value: "ibm-object-storage-plugin"
            - name: SAT_NAMESPACE
              value: "{{ namespace }}"
            - name: HELM_OPTIONS
              value: "platform=OpenShift,provider=rhocp,workerOS=redhat,kubeDriver=/usr/libexec/kubernetes,license={{ license }},cpu={{ cpu }},memory={{ memory }}"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-s3fs-silver
      labels:
        app.kubernetes.io/name: ibmcloud-object-storage-plugin
        app.kubernetes.io/version: "2.0.6"
    provisioner: ibm.io/ibmc-s3fs
    parameters:
      ibm.io/chunk-size-mb: "16"
      ibm.io/parallel-count: "2"
      ibm.io/multireq-max: "20"
      ibm.io/tls-cipher-suite: "ECDHE-RSA-AES128-GCM-SHA256"
      ibm.io/stat-cache-size: "100000"
      ibm.io/debug-level: "warn"
      ibm.io/curl-debug: "false"
      ibm.io/kernel-cache: "false"
      ibm.io/s3fs-fuse-retry-count: "5"
      ibm.io/iam-endpoint: "{{{ iam-endpoint }}}"
      ibm.io/object-store-endpoint: "{{{ cos-endpoint }}}"
      ibm.io/object-store-storage-class: "{{ cos-storage-class }}"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-s3fs-gold
      labels:
        app.kubernetes.io/name: ibmcloud-object-storage-plugin
        app.kubernetes.io/version: "2.0.6"
    provisioner: ibm.io/ibmc-s3fs
    parameters:
      ibm.io/chunk-size-mb: "52"
      ibm.io/parallel-count: "20"
      ibm.io/multireq-max: "20"
      ibm.io/tls-cipher-suite: "ECDHE-RSA-AES128-GCM-SHA256"
      ibm.io/stat-cache-size: "100000"
      ibm.io/debug-level: "warn"
      ibm.io/curl-debug: "false"
      ibm.io/kernel-cache: "true"
      ibm.io/s3fs-fuse-retry-count: "5"
      ibm.io/iam-endpoint: "{{{ iam-endpoint }}}"
      ibm.io/object-store-endpoint: "{{{ cos-endpoint }}}"
      ibm.io/object-store-storage-class: "{{ cos-storage-class }}"

