apiVersion: v1
kind: List
metadata:
  name: netapp-trident
  namespace: kube-system
  annotations:
    version: 20.07
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: netapp-file-gold
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      snapshots: "true"
      provisioningType: "thick"
      encryption: "true"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: netapp-file-silver
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      snapshots: "true"
      provisioningType: "thin"
      encryption: "true"
