---
apiVersion: v1
kind: List
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
  annotations:
    version: 0.9.14
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: aws-secret
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    data:
      key_id: "{{{ aws-access-key }}}"
      access_key: "{{{ aws-secret-access-key }}}"
  - apiVersion: storage.k8s.io/v1beta1
    kind: CSIDriver
    metadata:
      name: ebs.csi.aws.com
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    spec:
      attachRequired: true
      podInfoOnMount: false
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ebs-snapshot-controller
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ebs-csi-node-sa
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-attacher-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["csi.storage.k8s.io"]
        resources: ["csinodeinfos"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["volumeattachments"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["volumeattachments/status"]
        verbs: ["patch"]
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-provisioner-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "create", "delete"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshots"]
        verbs: ["get", "list"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotcontents"]
        verbs: ["get", "list"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["csinodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get", "watch", "list", "delete", "update", "create"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["volumeattachments"]
        verbs: ["get", "list", "watch"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-attacher-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-attacher-role
      apiGroup: rbac.authorization.k8s.io
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-provisioner-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-provisioner-role
      apiGroup: rbac.authorization.k8s.io
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-resizer-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims/status"]
        verbs: ["update", "patch"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-resizer-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namwspace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-resizer-role
      apiGroup: rbac.authorization.k8s.io
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-snapshot-controller-role
      labels:
        app.kubernetes.io/name:: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotcontents"]
        verbs: ["create", "get", "list", "watch", "update", "delete"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshots"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshots/status"]
        verbs: ["update"]
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-snapshotter-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    rules:
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "list"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotcontents"]
        verbs: ["create", "get", "list", "watch", "update", "delete"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotcontents/status"]
        verbs: ["update"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-snapshot-controller-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    subjects:
      - kind: ServiceAccount
        name: ebs-snapshot-controller
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-snapshot-controller-role
      apiGroup: rbac.authorization.k8s.io
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-snapshotter-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-snapshotter-role
      apiGroup: rbac.authorization.k8s.io
  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-snapshot-controller-leaderelection
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get", "watch", "list", "delete", "update", "create"]
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-snapshot-controller-leaderelection
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    subjects:
      - kind: ServiceAccount
        name: ebs-snapshot-controller
        namespace: kube-system
    roleRef:
      kind: Role
      name: ebs-snapshot-controller-leaderelection
      apiGroup: rbac.authorization.k8s.io
  - kind: StatefulSet
    apiVersion: apps/v1
    metadata:
      name: ebs-snapshot-controller
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 0.9.14
    spec:
      serviceName: ebs-snapshot-controller
      replicas: 1
      selector:
        matchLabels:
          app: ebs-snapshot-controller
          app.kubernetes.io/name: aws-ebs-csi-driver
      template:
        metadata:
          labels:
            app: ebs-snapshot-controller
            app.kubernetes.io/name: aws-ebs-csi-driver
            app.kubernetes.io/version: 0.9.14
        spec:
          serviceAccountName: ebs-snapshot-controller
          nodeSelector:
            kubernetes.io/os: linux
          tolerations:
            - operator: Exists
          containers:
            - name: snapshot-controller
              image: k8s.gcr.io/sig-storage/snapshot-controller:v3.0.3
              args:
                - --v=5
                - --leader-election=false
