apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ name }}"
  labels:
    volume-type: "block" # As per user specification; e.g.: block, file or object.
    storage-class-preference: "{{ storage-class-preference }}" # As per user specification; e.g.: 1, 2, ... 99.
    is-user-defined-class-class: "true" # As this is a user-defined storage class
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ is-default-class }}"
provisioner: block.csi.ibm.com
parameters:
  SpaceEfficiency: "{{ space-efficiency }}"   # Optional.
  pool: "{{ pool }}"
  csi.storage.k8s.io/provisioner-secret-name: "{{ secret-name }}"
  csi.storage.k8s.io/provisioner-secret-namespace: "{{ secret-namespace }}"
  csi.storage.k8s.io/controller-publish-secret-name: "{{ secret-name }}"
  csi.storage.k8s.io/controller-publish-secret-namespace: "{{ secret-namespace }}"
  csi.storage.k8s.io/controller-expand-secret-name: "{{ secret-name }}"
  csi.storage.k8s.io/controller-expand-secret-namespace: "{{ secret-namespace }}"
  csi.storage.k8s.io/fstype: "{{ fstype }}"   # Optional. Values ext4\xfs. The default is ext4.
  volume_name_prefix: "{{ prefix }}"      # Optional.
allowVolumeExpansion: {{ VolumeExpansion }} #false
