---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#   name: ibm-spectrum-scale-csi-lt
#provisioner: spectrumscale.csi.ibm.com
#parameters:
#    volBackendFs: "{{ vol-backend-fs }}"
#    volDirBasePath: "{{ vol-dir-base-path }}"
#reclaimPolicy: Delete

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ name }}"
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ is-default-class }}"
provisioner: spectrumscale.csi.ibm.com
parameters:
  volBackendFs: "{{ vol-backend-fs }}"
reclaimPolicy: Delete
