apiVersion: v1
kind: List
metadata:
  name: ibm-object-storage-plugin
  namespace: kube-system
  annotations:
    revision: 9  ## On every new release of the ibm-object-storage-plugin helm-chart revision should be updated to show users new version for cos-s3fs is available.
items:
  - apiVersion: satstorage.ibm.com/v1
    kind: SatStorageHelmChart
    metadata:
      name: ibm-object-storage-plugin
      namespace: ibm-satellite-storage
    spec:
      helm-repo-url: "raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm"
      helm-chart-name: "ibm-object-storage-plugin"
      helm-chart-namespace: "ibm-object-s3fs"
      helm-chart-version: "2.2.12"  ## On every new release of the ibm-object-storage-plugin helm-chart-version should be updated with new version
      release-name: "{{{ helm-release-name }}}"
      storage-template-revision: "9" ## On every new release of the ibm-object-storage-plugin helm-chart revision should be updated to show users new version for cos-s3fs is available.
      params:
        - license={{{ license }}}
        - cos.endpoint={{{ cos-endpoint }}}
        - cos.storageClass={{{ cos-storageclass }}}
        - cos.s3Provider={{{ cos-s3provider }}}
        {{#parameters }}
        - "{{{ item }}}"
        {{/parameters }}
