---
apiVersion: v1
kind: List
metadata:
    name: local-volume
    namespace: kube-system
    annotations:
        version: 1.0.0
        revision: 1
items:
    {{#install-local-storage-file}}
    {{#auto-discover-devices-file}}
    - apiVersion: local.storage.openshift.io/v1alpha1
      kind: LocalVolumeDiscovery
      metadata:
        name: auto-discover-devices-file-{{ local-volume-name }}
        namespace: local-storage
      spec:
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "{{ file-nodes-label-key }}"
                  operator: In
                  values:
                    - "{{ file-nodes-label-value }}"
    - apiVersion: local.storage.openshift.io/v1alpha1
      kind: LocalVolumeSet
      metadata:
        name: local-volumeset-file-{{ local-volume-name }}
        namespace: local-storage
      spec:
        deviceInclusionSpec:
          deviceTypes:
            - disk
            - part
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "{{ file-nodes-label-key }}"
                  operator: In
                  values:
                    - "{{ file-nodes-label-value }}"
        storageClassName: "sat-local-file-{{ local-volume-name }}"
        volumeMode: Filesystem
        fsType: "{{ fstype }}"
    {{/auto-discover-devices-file}}
    {{^auto-discover-devices-file}}
    - apiVersion: local.storage.openshift.io/v1
      kind: LocalVolume
      metadata:
          name: local-disk-file-{{ local-volume-name }}
          namespace: local-storage
      spec:
          nodeSelector:
              nodeSelectorTerms:
                  - matchExpressions:
                        - key: "{{ file-nodes-label-key }}"
                          operator: In
                          values:
                          - "{{ file-nodes-label-value }}"
          storageClassDevices:
              - storageClassName: "sat-local-file-{{ local-volume-name }}"
                volumeMode: Filesystem
                fsType: "{{ fstype }}"
                devicePaths:
                  {{#file-devicepath}}
                  - "{{{ item }}}"
                  {{/file-devicepath}}
    {{/auto-discover-devices-file}}
    {{/install-local-storage-file}}
    {{#install-local-storage-block}}
    {{#auto-discover-devices-block}}
    - apiVersion: local.storage.openshift.io/v1alpha1
      kind: LocalVolumeDiscovery
      metadata:
        name: auto-discover-devices-block-{{ local-volume-name }}
        namespace: local-storage
      spec:
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "{{ block-nodes-label-key }}"
                  operator: In
                  values:
                    - "{{ block-nodes-label-value }}"
    - apiVersion: local.storage.openshift.io/v1alpha1
      kind: LocalVolumeSet
      metadata:
        name: local-volumeset-block-{{ local-volume-name }}
        namespace: local-storage
      spec:
        deviceInclusionSpec:
          deviceTypes:
            - disk
            - part
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "{{ block-nodes-label-key }}"
                  operator: In
                  values:
                    - "{{ block-nodes-label-value }}"
        storageClassName: "sat-local-block-{{ local-volume-name }}"
        volumeMode: Block
    {{/auto-discover-devices-block}}
    {{^auto-discover-devices-block}}
    - apiVersion: local.storage.openshift.io/v1
      kind: LocalVolume
      metadata:
        name: local-disk-block-{{ local-volume-name }}
        namespace: local-storage
      spec:
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "{{ block-nodes-label-key }}"
                  operator: In
                  values:
                    - "{{ block-nodes-label-value }}"
        storageClassDevices:
          - storageClassName: "sat-local-block-{{ local-volume-name }}"
            volumeMode: Block
            devicePaths:
              {{#block-devicepath}}
              - "{{{ item }}}"
              {{/block-devicepath}}
    {{/auto-discover-devices-block}}
    {{/install-local-storage-block}}
    - apiVersion: satstorage.ibm.com/v1
      kind: SatStorageCleanup
      metadata:
          name: satstoragecleanup-local-storage-{{ local-volume-name }}
          namespace: "ibm-satellite-storage"
      spec:
          template-name: "local-storage"
          template-version: "1.0.0"
          template-namespace: "local-storage"
          config-params-for-cleanup:
          - local-volume-name="{{ local-volume-name }}"
          - install-local-storage-file="{{ install-local-storage-file }}"
          - auto-discover-devices-file="{{ auto-discover-devices-file }}"
          - install-local-storage-block="{{ install-local-storage-block }}"
          - auto-discover-devices-block="{{ auto-discover-devices-block }}"

          
