---
apiVersion: v1   
kind: List
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
  annotations:
    version: 1.5.1
    revision: 1
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: aws-secret
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    data:
      key_id: "{{{ aws-access-key }}}"
      access_key: "{{{ aws-secret-access-key }}}"
  - apiVersion: storage.k8s.io/v1
    kind: CSIDriver
    metadata:
      name: ebs.csi.aws.com
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    spec:
      attachRequired: true
      podInfoOnMount: false
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ebs-csi-node-sa
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-attacher-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["csi.storage.k8s.io"]
        resources: ["csinodeinfos"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["volumeattachments"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["volumeattachments/status"]
        verbs: ["patch"]
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-provisioner-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "create", "delete"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshots"]
        verbs: ["get", "list"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotcontents"]
        verbs: ["get", "list"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["csinodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get", "watch", "list", "delete", "update", "create"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["volumeattachments"]
        verbs: ["get", "list", "watch"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-attacher-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-attacher-role
      apiGroup: rbac.authorization.k8s.io
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-provisioner-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-provisioner-role
      apiGroup: rbac.authorization.k8s.io
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-resizer-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    rules:
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims/status"]
        verbs: ["update", "patch"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-resizer-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-resizer-role
      apiGroup: rbac.authorization.k8s.io
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-external-snapshotter-role
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    rules:
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "list"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotcontents"]
        verbs: ["create", "get", "list", "watch", "update", "delete"]
      - apiGroups: ["snapshot.storage.k8s.io"]
        resources: ["volumesnapshotcontents/status"]
        verbs: ["update"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ebs-csi-snapshotter-binding
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    subjects:
      - kind: ServiceAccount
        name: ebs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ebs-external-snapshotter-role
      apiGroup: rbac.authorization.k8s.io
  - kind: DaemonSet
    apiVersion: apps/v1
    metadata:
      name: ebs-csi-node
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    spec:
      selector:
        matchLabels:
          app: ebs-csi-node
          app.kubernetes.io/name: aws-ebs-csi-driver
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: "10%"
      template:
        metadata:
          labels:
            app: ebs-csi-node
            app.kubernetes.io/name: aws-ebs-csi-driver
            app.kubernetes.io/version: 1.5.1
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                    - fargate
          nodeSelector:
            kubernetes.io/os: linux
#           hostNetwork: true
          serviceAccountName: ebs-csi-node-sa
          priorityClassName: system-cluster-critical
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
            - operator: Exists
              effect: NoExecute
              tolerationSeconds: 300
          containers:
            - name: ebs-plugin
              securityContext:
                privileged: true
              image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.1
              imagePullPolicy: IfNotPresent
              args:
                - node
                - --endpoint=$(CSI_ENDPOINT)
                - --logtostderr
                - --v=2   
              env:
                - name: CSI_ENDPOINT
                  value: unix:/csi/csi.sock
                - name: CSI_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: kubelet-dir
                  mountPath: /var/data/kubelet
                  mountPropagation: "Bidirectional"
                - name: plugin-dir
                  mountPath: /csi
                - name: device-dir
                  mountPath: /dev
              ports:
                - name: healthz
                  containerPort: 9808
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 5
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            - name: node-driver-registrar
              image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
              imagePullPolicy: IfNotPresent
              args:
                - --csi-address=$(ADDRESS)
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --v=2
              env:
                - name: ADDRESS
                  value: /csi/csi.sock
                - name: DRIVER_REG_SOCK_PATH
                  value: /var/data/kubelet/plugins/ebs.csi.aws.com/csi.sock
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
                - name: registration-dir
                  mountPath: /registration
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            - name: liveness-probe
              image: k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
              imagePullPolicy: IfNotPresent
              args:
                - --csi-address=/csi/csi.sock
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
          volumes:
            - name: kubelet-dir
              hostPath:
                path: /var/data/kubelet
                type: Directory
            - name: plugin-dir
              hostPath:
                path: /var/data/kubelet/plugins/ebs.csi.aws.com/
                type: DirectoryOrCreate
            - name: registration-dir
              hostPath:
                path: /var/data/kubelet/plugins_registry/
                type: Directory
            - name: device-dir
              hostPath:
                path: /dev
                type: Directory
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ebs-csi-controller
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: ebs-csi-controller
          app.kubernetes.io/name: aws-ebs-csi-driver
      template:
        metadata:
          labels:
            app: ebs-csi-controller
            app.kubernetes.io/name: aws-ebs-csi-driver
            app.kubernetes.io/version: 1.5.1
        spec:
          nodeSelector:
            kubernetes.io/os: linux
          serviceAccountName: ebs-csi-controller-sa
          priorityClassName: system-cluster-critical
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
            - operator: Exists
              effect: NoExecute
              tolerationSeconds: 300
          containers:
            - name: ebs-plugin
              image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.1
              imagePullPolicy: IfNotPresent
              args:
                - controller
                - --endpoint=$(CSI_ENDPOINT)
                - --logtostderr
                - --v=2
              env:
                - name: CSI_ENDPOINT
                  value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
                - name: CSI_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: key_id
                      optional: true
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: access_key
                      optional: true
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              ports:
                - name: healthz
                  containerPort: 9808
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 5
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 5
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            - name: csi-provisioner
              image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
              imagePullPolicy: IfNotPresent
              args:
                - --csi-address=$(ADDRESS)
                - --v=2
                - --feature-gates=Topology=true
                - --leader-election=true
                - --extra-create-metadata
                - --default-fstype=ext4
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            - name: csi-attacher
              image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
              imagePullPolicy: IfNotPresent
              args:
                - --csi-address=$(ADDRESS)
                - --v=2
                - --leader-election=true
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            - name: csi-snapshotter
              image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
              imagePullPolicy: IfNotPresent
              args:
                - --csi-address=$(ADDRESS)
                - --leader-election=true
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            - name: csi-resizer
              image: k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
              imagePullPolicy: IfNotPresent
              args:
                - --csi-address=$(ADDRESS)
                - --v=2
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            - name: liveness-probe
              image: k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
              imagePullPolicy: IfNotPresent
              args:
                - --csi-address=/csi/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /csi
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
          volumes:
            - name: socket-dir
              emptyDir: {}
  - kind: PodDisruptionBudget
    apiVersion: policy/v1beta1
    metadata:
      name: ebs-csi-controller
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    spec:
      selector:
        matchLabels:
          app: ebs-csi-controller
      minAvailable: 2

