---
apiVersion: v1
kind: List
metadata:
  name: aws-ebs-csi-driver-sc
  namespace: kube-system
  annotations:
    version: 1.5.1
items:
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-aws-block-gold
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    provisioner: ebs.csi.aws.com
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      csi.storage.k8s.io/fstype: ext4
      type: io2
      iopsPerGB: "10"
      encrypted: "true"
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-aws-block-silver
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    provisioner: ebs.csi.aws.com
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      csi.storage.k8s.io/fstype: ext4
      type: gp3
      encrypted: "true"
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-aws-block-bronze
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    provisioner: ebs.csi.aws.com
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      csi.storage.k8s.io/fstype: ext4
      type: st1
      encrypted: "true"
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-aws-block-gold-metro
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    provisioner: ebs.csi.aws.com
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    parameters:
      csi.storage.k8s.io/fstype: ext4
      type: io2
      iopsPerGB: "10"
      encrypted: "true"
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-aws-block-silver-metro
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    provisioner: ebs.csi.aws.com
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    parameters:
      csi.storage.k8s.io/fstype: ext4
      type: gp3
      encrypted: "true"
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-aws-block-bronze-metro
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.5.1
    provisioner: ebs.csi.aws.com
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    parameters:
      csi.storage.k8s.io/fstype: ext4
      type: st1
      Encrypted: "true"
