apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ name }}"
  labels:
    app.kubernetes.io/name: "netapp-ontap-san"
    app.kubernetes.io/version: "v22.04"
    app.kubernetes.io/revision: "17"
    volume-type: "block"
    storage-class-preference: "{{ storage-class-preference }}"
    is-user-defined-class: "true"
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ is-default-class }}"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  selector: "{{ selector }}"
  fsType: "{{ fsType }}"
allowVolumeExpansion: {{ allowVolumeExpansion }}
volumeBindingMode: "{{ volumeBindingMode }}"
