---
apiVersion: v1
kind: List
metadata:
  name: azuredisk-csi-driver-sc
  namespace: kube-system
  annotations:
    version: 1.23.0
items:
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-platinum-metro
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "1"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: UltraSSD_LRS
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-platinum
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "5"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: UltraSSD_LRS
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-gold-metro
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "2"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: Premium_LRS
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-gold
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "6"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: Premium_LRS
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-silver-metro
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "3"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: StandardSSD_LRS
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-silver
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "7"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: StandardSSD_LRS
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-bronze-metro
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "4"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: Standard_LRS
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-block-bronze
      labels:
        app.kubernetes.io/name: azuredisk-csi-driver
        app.kubernetes.io/version: 1.23.0
        volume-type: "block"
        storage-class-preference: "8"
        is-user-defined-class: "false"
    provisioner: disk.csi.azure.com
    parameters:
      skuname: Standard_LRS
    volumeBindingMode: Immediate
    allowVolumeExpansion: true