---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ storage-class-name }}"
  labels:
    app.kubernetes.io/name: "ibm-spectrum-fusion"
    app.kubernetes.io/version: "v2.4.0"
    app.kubernetes.io/revision: "1"
    volume-type: "block"
    storage-class-preference: "{{ storage-class-preference }}"
    is-user-defined-class: "true"
provisioner: spectrumscale.csi.ibm.com
parameters:
  volBackendFs: "{{ primary-vol-backend-fs }}"
  clusterId: "{{ primary-cluster-id }}"
reclaimPolicy: Delete

