apiVersion: v1
kind: List
metadata:
  name: netapp-trident-san
  namespace: kube-system
  annotations:
    version: 20.07
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold
      labels:
        volume-type: "block"
        storage-class-preference: "4" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=gold"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver
      labels:
        volume-type: "block"
        storage-class-preference: "5" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=silver"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze
      labels:
        volume-type: "block"
        storage-class-preference: "6" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=bronze"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-metro
      labels:
        volume-type: "block"
        storage-class-preference: "1" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=gold"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-metro
      labels:
        volume-type: "block"
        storage-class-preference: "2" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=silver"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-metro
      labels:
        volume-type: "block"
        storage-class-preference: "3" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=bronze"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
