apiVersion: v1
kind: List
metadata:
  name: netapp-trident-san
  namespace: kube-system
  annotations:
    version: 20.07
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=gold"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=silver"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "performance=bronze"
