---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: "{{ storage-class-name }}"
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "{{ vol-backend-fs }}"
    volDirBasePath: "{{ vol-dir-base-path }}"
reclaimPolicy: Delete