apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ name }}"
  labels:
    app.kubernetes.io/name: vsphere-csi-driver
    app.kubernetes.io/version: 2.5.0
    volume-type: "{{ volume-type }}"
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ is-default-class }}"
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "{{ datastoreurl }}"
  storagepolicyname: "{{ storagepolicyname }}"
volumeBindingMode: "{{ volumeBindingMode }}"

