---
apiVersion: v1
kind: List
metadata:
  name: ridge-csi-driver
  namespace: kube-system
  annotations:
    version: "1.0.0"
    revision: "1"
items:
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: csi-ridge-controller
      namespace: kube-system
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: csi-ridge-controller
      serviceName: csi-ridge
      template:
        metadata:
          labels:
            app: csi-ridge-controller
            role: csi-ridge
            app.kubernetes.io/name: ridge-csi-driver
            app.kubernetes.io/version: 1.0.0
            cloud.ridge.co/managed: "true"
        spec:
          volumes:
            - name: socket-dir
              emptyDir: {}
            - name: tectonic-etc
              hostPath:
                path: /opt/tectonic/etc
                type: Directory
            - name: init-unit
              hostPath:
                path: /etc/systemd/system/app-init.service
          containers:
            - name: csi-provisioner
              image: {{{ csi-provisioner-image }}}
              args:
                {{#provisioner-parameters }}
                   - "{{{ item }}}"
                {{/provisioner-parameters }}
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              imagePullPolicy: IfNotPresent
            - name: csi-attacher
              image: {{{ csi-attacher-image }}}
              args:
                {{#attacher-parameters }}
                   - "{{{ item }}}"
                {{/attacher-parameters }}
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              imagePullPolicy: IfNotPresent
            - name: csi-ridge-plugin
              image: {{{ ridge-csi-statefulset-image }}}
              args:
                {{#statefulset-parameters }}
                - "{{{ item }}}"
                {{/statefulset-parameters }}
              env:
                - name: CSI_ENDPOINT
                  value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
                - name: tectonic-etc
                  readOnly: true
                  mountPath: /opt/tectonic/etc
                - name: init-unit
                  readOnly: true
                  mountPath: /etc/systemd/system/app-init.service
              imagePullPolicy: IfNotPresent
{{#install-resizer}}
            - name: csi-resizer
              image: {{{ csi-resizer-image }}}
              args:
                {{#resizer-parameters }}
                   - "{{{ item }}}"
                {{/resizer-parameters }}
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              imagePullPolicy: IfNotPresent
{{/install-resizer}}
          serviceAccount: csi-ridge-controller-sa
          tolerations:
            - operator: Exists
          priorityClassName: system-cluster-critical
          dnsConfig:
            options:
              - name: single-request-reopen
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: csi-ridge-controller-sa
      namespace: kube-system
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: csi-ridge-provisioner-role
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"
    rules:
      - verbs:
          - get
          - list
        apiGroups:
          - ''
        resources:
          - secrets
      - verbs:
          - get
          - list
          - watch
          - create
          - delete
        apiGroups:
          - ''
        resources:
          - persistentvolumes
      - verbs:
          - get
          - list
          - watch
          - update
        apiGroups:
          - ''
        resources:
          - persistentvolumeclaims
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - storage.k8s.io
        resources:
          - storageclasses
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - storage.k8s.io
        resources:
          - csinodes
      - verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
        apiGroups:
          - ''
        resources:
          - events
      - verbs:
          - get
          - list
        apiGroups:
          - snapshot.storage.k8s.io
        resources:
          - volumesnapshots
      - verbs:
          - get
          - list
        apiGroups:
          - snapshot.storage.k8s.io
        resources:
          - volumesnapshotcontents
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - ''
        resources:
          - nodes
      - verbs:
          - list
        apiGroups:
          - ''
        resources:
          - pods
      - verbs:
          - patch
        apiGroups:
          - ''
        resources:
          - persistentvolumeclaims/status
      - verbs:
          - patch
        apiGroups:
          - storage.k8s.io
        resources:
          - volumeattachments/status
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: csi-ridge-provisioner-binding
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"
    subjects:
      - kind: ServiceAccount
        name: csi-ridge-controller-sa
        namespace: kube-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: csi-ridge-provisioner-role
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: csi-ridge-attacher-role
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"
    rules:
      - verbs:
          - get
          - list
          - watch
          - update
          - patch
        apiGroups:
          - ''
        resources:
          - persistentvolumes
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - ''
        resources:
          - nodes
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - storage.k8s.io
        resources:
          - csinodes
      - verbs:
          - get
          - list
          - watch
          - update
          - patch
        apiGroups:
          - storage.k8s.io
        resources:
          - volumeattachments
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: csi-ridge-attacher-binding
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"
    subjects:
      - kind: ServiceAccount
        name: csi-ridge-controller-sa
        namespace: kube-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: csi-ridge-attacher-role
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: csi-ridge-node
      namespace: kube-system
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"
    spec:
      selector:
        matchLabels:
          app: csi-ridge-node
      template:
        metadata:
          labels:
            app: csi-ridge-node
            role: csi-ridge
            app.kubernetes.io/name: ridge-csi-driver
            app.kubernetes.io/version: 1.0.0
            cloud.ridge.co/managed: "true"
        spec:
          volumes:
            - name: registration-dir
              hostPath:
                path: /var/data/kubelet/plugins_registry/
                type: DirectoryOrCreate
            - name: plugin-dir
              hostPath:
                path: /var/data/kubelet/plugins/driver.csi.ridge.com
                type: DirectoryOrCreate
            - name: pods-mount-dir
              hostPath:
                path: /var/data/kubelet
                type: Directory
            - name: device-dir
              hostPath:
                path: /dev
            - name: usr-sbin
              hostPath:
                path: /usr/sbin
            - name: lib64
              hostPath:
                path: /lib64
            - name: tectonic-etc
              hostPath:
                path: /opt/tectonic/etc
                type: Directory
            - name: init-unit
              hostPath:
                path: /etc/systemd/system/app-init.service
          containers:
            - name: csi-ridge-plugin
              image: {{{ ridge-csi-daemonset-image }}}
              args:
                {{#daemonset-parameters }}
                - "{{{ item }}}"
                {{/daemonset-parameters }}
              env:
                - name: CSI_ENDPOINT
                  value: unix:///csi/csi.sock
                - name: KUBE_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi/
                - name: pods-mount-dir
                  mountPath: /var/data/kubelet
                  mountPropagation: Bidirectional
                - name: device-dir
                  mountPath: /dev
                - name: usr-sbin
                  mountPath: /usr/sbin
                - name: lib64
                  mountPath: /lib64
                - name: tectonic-etc
                  readOnly: true
                  mountPath: /opt/tectonic/etc
                - name: init-unit
                  readOnly: true
                  mountPath: /etc/systemd/system/app-init.service
                - name: registration-dir
                  mountPath: /registration/
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities:
                  add:
                    - SYS_ADMIN
                privileged: true
                allowPrivilegeEscalation: true
          serviceAccount: csi-ridge-node-sa
          hostNetwork: true
          tolerations:
            - operator: Exists
          priorityClassName: system-node-critical
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: csi-ridge-node-sa
      namespace: kube-system
      labels:
        app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
        cloud.ridge.co/managed: "true"