---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ name }}
  labels:
    volume-type: block
    storage-class-preference: "{{ storage-class-preference }}"
    is-user-defined-class: "true"
    cloud.ridge.co/managed: "true"
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ is-default-class }}
provisioner: driver.csi.ridge.com
allowVolumeExpansion: {{ allowVolumeExpansion }}
volumeBindingMode: WaitForFirstConsumer

