apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{name}}"
provisioner: pd.csi.storage.gke.io
parameters:
  type: "{{type}}"
  replication-type: regional-pd
volumeBindingMode: "{{volumeBindingMode}}"