apiVersion: v1
kind: List
metadata:
  name: netapp-trident-san
  namespace: kube-system
  annotations:
    version: 21.04
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-encrypted
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold-encrypted"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-encrypted
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver-encrypted"
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-encrypted
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze-encrypted"