apiVersion: v1
kind: List
metadata:
  name: netapp-trident-san
  namespace: kube-system
  annotations:
    version: 21.04
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-encrypted
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-encrypted
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-encrypted
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-metro
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-metro
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-metro
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-encrypted-metro
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-encrypted-metro
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-encrypted-metro
      labels:
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
