apiVersion: v1
kind: List
metadata:
  name: netapp-trident-san
  namespace: kube-system
  annotations:
    version: 21.04
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold
      labels:
        volume-type: "block"
        storage-class-preference: "4" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver
      labels:
        volume-type: "block"
        storage-class-preference: "8" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze
      labels:
        volume-type: "block"
        storage-class-preference: "12" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-encrypted
      labels:
        volume-type: "block"
        storage-class-preference: "2" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-encrypted
      labels:
        volume-type: "block"
        storage-class-preference: "6" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-encrypted
      labels:
        volume-type: "block"
        storage-class-preference: "10" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-metro
      labels:
        volume-type: "block"
        storage-class-preference: "3" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-metro
      labels:
        volume-type: "block"
        storage-class-preference: "7" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-metro
      labels:
        volume-type: "block"
        storage-class-preference: "11" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-gold-encrypted-metro
      labels:
        volume-type: "block"
        storage-class-preference: "1" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-gold-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-silver-encrypted-metro
      labels:
        volume-type: "block"
        storage-class-preference: "5" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-silver-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-block-bronze-encrypted-metro
      labels:
        volume-type: "block"
        storage-class-preference: "9" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-san"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "24"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-san"
      selector: "quality=block-bronze-encrypted"
      fsType: "ext4"
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
