---
apiVersion: v1
kind: List
metadata:
  name: azurefile-csi-driver-sc
  namespace: kube-system
  annotations:
    version: 1.9.0
items:
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-platinum-metro
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "file"
        storage-class-preference: "1"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: UltraSSD_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-platinum
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "file"
        storage-class-preference: "5"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: UltraSSD_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: Immediate
    allowVolumeExpansion: true

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-gold-metro
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "file"
        storage-class-preference: "2"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: Premium_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-gold
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "file"
        storage-class-preference: "6"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: Premium_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: Immediate
    allowVolumeExpansion: true

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-silver-metro
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "file"
        storage-class-preference: "3"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: StandardSSD_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-silver
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "file"
        storage-class-preference: "7"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: StandardSSD_LRS
      protocol: nfs
    volumeBindingMode: Immediate
    allowVolumeExpansion: true

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-bronze-metro
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "block"
        storage-class-preference: "4"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: Standard_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-azure-file-bronze
      labels:
        app.kubernetes.io/name: azurefile-csi-driver
        app.kubernetes.io/version: 1.9.0
        volume-type: "block"
        storage-class-preference: "8"
        is-user-defined-class: "false"
    provisioner: file.csi.azure.com
    parameters:
      skuname: Standard_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
