apiVersion: v1
kind: List
metadata:
  name: netapp-trident-nas
  namespace: kube-system
  annotations:
    version: 20.07
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: trident-kubectl-nas
      namespace: "trident"
    spec:
      serviceAccountName: trident-kubectl-sa
      containers:
        - name: trident-kubectl-nas
          image: nkkashyap/ibm-tridentctl:v002
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: "trident"
            - name: DRIVER_Name
              value: "ontap-nas"
            - name: MGMT_LIF
              value: "{{{ managementLIF }}}"
            - name: DATA_LIF
              value: "{{{ dataLIF }}}"
            - name: SVM_Name
              value: "{{{ svm }}}"
            - name: USER_Name
              value: "{{{ username }}}"
            - name: USER_Password
              value: "{{{ password }}}"
            - name: EXPORT_Policy
              value: "{{{ exportPolicy }}}"
            - name: LIMIT_VolumeSize
              value: "{{{ limitVolumeSize }}}"
            - name: LIMIT_AggregateUsage
              value: "{{{ limitAggregateUsage }}}"
            - name: NFS_MountOptions
              value: "{{{ nfsMountOptions }}}"
