apiVersion: v1
kind: List
metadata:
  name: netapp-trident-nas
  namespace: kube-system
  annotations:
    version: 20.07
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-gold
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "performance=gold"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-silver
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "performance=silver"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-bronze
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "performance=bronze"
    allowVolumeExpansion: True
