apiVersion: v1
kind: List
metadata:
  name: netapp-trident-nas
  namespace: kube-system
  annotations:
    version: 20.07
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-gold
      labels:
        volume-type: "file"
        storage-class-preference: "1" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "performance=gold"
    allowVolumeExpansion: true
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-silver
      labels:
        volume-type: "file"
        storage-class-preference: "2" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "performance=silver"
    allowVolumeExpansion: true
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-bronze
      labels:
        volume-type: "file"
        storage-class-preference: "3" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "performance=bronze"
    allowVolumeExpansion: true
