---
apiVersion: v1
kind: List
metadata:
  name: aws-efs-csi-driver
  namespace: kube-system
  annotations:
    version: 1.2.2
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: aws-secret
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        app.kubernetes.io/version: 1.2.2
    data:
      key_id: "{{{ aws-access-key }}}"
      access_key: "{{{ aws-secret-access-key }}}"
  - apiVersion: storage.k8s.io/v1beta1
    kind: CSIDriver
    metadata:
      name: efs.csi.aws.com
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
    spec:
      attachRequired: false
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: efs-csi-node
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: efs-csi-external-provisioner-role
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "create", "delete"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["csinodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get", "watch", "list", "delete", "update", "create"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: efs-csi-provisioner-binding
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
    subjects:
      - kind: ServiceAccount
        name: efs-csi-controller-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: efs-csi-external-provisioner-role
      apiGroup: rbac.authorization.k8s.io
  - kind: DaemonSet
    apiVersion: apps/v1
    metadata:
      name: efs-csi-node
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
    spec:
      selector:
        matchLabels:
          app: efs-csi-node
          app.kubernetes.io/name: aws-efs-csi-driver
          app.kubernetes.io/version: 1.2.2
      template:
        metadata:
          labels:
            app: efs-csi-node
            app.kubernetes.io/name: aws-efs-csi-driver
            app.kubernetes.io/version: 1.2.2
        spec:
          nodeSelector:
            kubernetes.io/os: linux
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: eks.amazonaws.com/compute-type
                        operator: NotIn
                        values:
                          - fargate
          hostNetwork: true
          priorityClassName: system-node-critical
          tolerations:
            - operator: Exists
          serviceAccountName: efs-csi-node
          containers:
            - name: efs-plugin
              securityContext:
                privileged: true
              image: "amazon/aws-efs-csi-driver:v1.2.0"
              args:
                - --endpoint=$(CSI_ENDPOINT)
                - --logtostderr
                - --v=5
              env:
                - name: CSI_ENDPOINT
                  value: unix:/csi/csi.sock
              volumeMounts:
                - name: kubelet-dir
                  mountPath: /var/data/kubelet
                  mountPropagation: "Bidirectional"
                - name: plugin-dir
                  mountPath: /csi
                - name: efs-state-dir
                  mountPath: /var/run/efs
                - name: efs-utils-config
                  mountPath: /etc/amazon/efs
                - name: efs-utils-config-legacy
                  mountPath: /etc/amazon/efs-legacy
              ports:
                - name: healthz
                  containerPort: 9809
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 3
                periodSeconds: 2
                failureThreshold: 5
            - name: cs-driver-registrar
              image: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.0.1-eks-1-18-1
              args:
                - --csi-address=$(ADDRESS)
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --v=5
              env:
                - name: ADDRESS
                  value: /csi/csi.sock
                - name: DRIVER_REG_SOCK_PATH
                  value: /var/data/kubelet/plugins/efs.csi.aws.com/csi.sock
                - name: KUBE_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
                - name: registration-dir
                  mountPath: /registration
            - name: liveness-probe
              image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.1.0-eks-1-18-1
              args:
                - --csi-address=/csi/csi.sock
                - --health-port=9809
                - --v=5
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
          volumes:
            - name: kubelet-dir
              hostPath:
                path: /var/data/kubelet
                type: Directory
            - name: plugin-dir
              hostPath:
                path: /var/data/kubelet/plugins/efs.csi.aws.com/
                type: DirectoryOrCreate
            - name: registration-dir
              hostPath:
                path: /var/data/kubelet/plugins_registry/
                type: Directory
            - name: efs-state-dir
              hostPath:
                path: /var/run/efs
                type: DirectoryOrCreate
            - name: efs-utils-config
              hostPath:
                path: /etc/amazon/efs
                type: DirectoryOrCreate
            - name: efs-utils-config-legacy
              hostPath:
                path: /etc/amazon/efs
                type: DirectoryOrCreate
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: efs-csi-controller
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: efs-csi-controller
          app.kubernetes.io/name: aws-efs-csi-driver
      template:
        metadata:
          labels:
            app: efs-csi-controller
            app.kubernetes.io/name: aws-efs-csi-driver
            app.kubernetes.io/version: 1.2.2
        spec:
          nodeSelector:
            kubernetes.io/os: linux
          serviceAccountName: efs-csi-controller-sa
          priorityClassName: system-cluster-critical
          tolerations:
            - operator: Exists
          containers:
            - name: efs-plugin
              securityContext:
                privileged: true
              image: amazon/aws-efs-csi-driver:v1.2.0
              imagePullPolicy: IfNotPresent
              args:
                - --endpoint=$(CSI_ENDPOINT)
                - --logtostderr
                - --v=5
              env:
                - name: CSI_ENDPOINT
                  value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: key_id
                      optional: true
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: access_key
                      optional: true
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
              ports:
                - name: healthz
                  containerPort: 9808
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 5
            - name: csi-provisioner
              image: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v2.0.3-eks-1-18-1
              args:
                - --csi-address=$(ADDRESS)
                - --v=5
                - --feature-gates=Topology=true
                - --leader-election
              env:
                - name: ADDRESS
                  value: /var/lib/csi/sockets/pluginproxy/csi.sock
              volumeMounts:
                - name: socket-dir
                  mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: liveness-probe
              image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.1.0-eks-1-18-1
              args:
                - --csi-address=/csi/csi.sock
                - --health-port=9808
              volumeMounts:
                - name: socket-dir
                  mountPath: /csi
          volumes:
            - name: socket-dir
              emptyDir: {}
