apiVersion: v1
kind: List
metadata:
  name: aws-efs-csi-driver-sc
  namespace: kube-system
  annotations:
    version: 1.2.2
items:
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: "{{ name }}"
      annotations:
        storageclass.kubernetes.io/is-default-class: "{{ is-default-class }}"
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.2.2
    mountOptions:
      - tls
    provisioner: efs.csi.aws.com
    parameters:
      provisioningMode: efs-ap
      fileSystemId: "{{ fsid }}"
      directoryPerms: "{{ directory-perms }}"
      gidRangeStart: "{{ gid-range-start }}"
      gidRangeEnd: "{{ gid-range-end }}"
      basePath: "{{ base-path }}"
