apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ name }}"
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ is-default-class }}"
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
    app.kubernetes.io/version: 1.2.2
mountOptions:
  - tls
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: "{{ fileSystemId }}"
  directoryPerms: "{{ directoryPerms }}"
  gidRangeStart: "{{ gidRangeStart }}"
  gidRangeEnd: "{{ gidRangeEnd }}"
  basePath: "{{ basePath }}"
