---
apiVersion: v1
kind: List
metadata:
  name: local-storage-operator
  namespace: kube-system
  annotations:
    version: 1.0.0
    revision: 1
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: local-storage
      labels:
        deploy.razee.io/Reconcile: "false"
  - apiVersion: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    metadata:
      name: local-operator-group
      namespace: local-storage
    spec:
      targetNamespaces:
        - local-storage
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: local-storage-operator
      namespace: local-storage
    spec:
      channel: "stable"
      installPlanApproval: Automatic
      name: local-storage-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
  - apiVersion: satstorage.ibm.com/v1
    kind: SatStorageCleanup
    metadata:
      name: satstoragecleanup-local-storage-operator
      namespace: "ibm-satellite-storage"
    spec:
      template-name: "local-storage-operator"
      template-version: "1.0.0"
      template-namespace: "local-storage"
