apiVersion: v1
kind: List
metadata:
  name: netapp-trident-nas
  namespace: kube-system
  annotations:
    version: 21.04
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-gold
      labels:
        volume-type: "file"
        storage-class-preference: "2" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "16"
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-gold"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-silver
      labels:
        volume-type: "file"
        storage-class-preference: "4" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "16"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-silver"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-bronze
      labels:
        volume-type: "file"
        storage-class-preference: "6" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "16"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-bronze"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-gold-encrypted
      labels:
        volume-type: "file"
        storage-class-preference: "1" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "16"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-gold-encrypted"
    allowVolumeExpansion: true
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-silver-encrypted
      labels:
        volume-type: "file"
        storage-class-preference: "3" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "16"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-silver-encrypted"
    allowVolumeExpansion: true
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-bronze-encrypted
      labels:
        volume-type: "file"
        storage-class-preference: "5" # As per vendor specification; e.g.: 1, 2, ... 99.
        is-user-defined-class: "false"
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "16"
    provisioner: csi.trident.netapp.io
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-bronze"
    allowVolumeExpansion: true
