apiVersion: v1
kind: List
metadata:
  name: netapp-trident-nas
  namespace: kube-system
  annotations:
    version: 21.04
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-gold
      labels:
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-gold"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-silver
      labels:
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-silver"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-bronze
      labels:
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-bronze"
    allowVolumeExpansion: True
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-gold-encrypted
      labels:
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-gold-encrypted"
    allowVolumeExpansion: true
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-silver-encrypted
      labels:
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-silver-encrypted"
    allowVolumeExpansion: true
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: sat-netapp-file-bronze-encrypted
      labels:
        app.kubernetes.io/name: "netapp-ontap-nas"
        app.kubernetes.io/version: "v21.04"
        app.kubernetes.io/revision: "3"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
      selector: "quality=file-bronze"
    allowVolumeExpansion: true
