---
apiVersion: v1
kind: List
metadata:
  name: aws-efs-csi-driver
  namespace: kube-system
  annotations:
    version: 1.0.0
items:
  - apiVersion: storage.k8s.io/v1beta1
    kind: CSIDriver
    metadata:
      name: efs.csi.aws.com
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.0.0
    spec:
      attachRequired: false
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: efs-csi-node
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.0.0
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: sat-aws-file-gold
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.0.0
    provisioner: efs.csi.aws.com
  - kind: DaemonSet
    apiVersion: apps/v1
    metadata:
      name: efs-csi-node
      namespace: kube-system
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
        app.kubernetes.io/version: 1.0.0
    spec:
      selector:
        matchLabels:
          app: efs-csi-node
          app.kubernetes.io/name: aws-efs-csi-driver
          app.kubernetes.io/version: 1.0.0
      template:
        metadata:
          labels:
            app: efs-csi-node
            app.kubernetes.io/name: aws-efs-csi-driver
            app.kubernetes.io/version: 1.0.0
        spec:
          nodeSelector:
            kubernetes.io/os: linux
          hostNetwork: true
          priorityClassName: system-node-critical
          tolerations:
            - operator: Exists
          serviceAccountName: efs-csi-node
          containers:
            - name: efs-plugin
              securityContext:
                privileged: true
              image: "amazon/aws-efs-csi-driver:v1.0.0"
              args:
                - --endpoint=$(CSI_ENDPOINT)
                - --logtostderr
                - --v=5
              env:
                - name: CSI_ENDPOINT
                  value: unix:/csi/csi.sock
              volumeMounts:
                - name: kubelet-dir
                  mountPath: /var/data/kubelet
                  mountPropagation: "Bidirectional"
                - name: plugin-dir
                  mountPath: /csi
                - name: efs-state-dir
                  mountPath: /var/run/efs
                - name: efs-utils-config
                  mountPath: /etc/amazon/efs
              ports:
                - name: healthz
                  containerPort: 9809
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 3
                periodSeconds: 2
                failureThreshold: 5
            - name: cs-driver-registrar
              image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
              args:
                - --csi-address=$(ADDRESS)
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --v=5
              env:
                - name: ADDRESS
                  value: /csi/csi.sock
                - name: DRIVER_REG_SOCK_PATH
                  value: /var/data/kubelet/plugins/efs.csi.aws.com/csi.sock
                - name: KUBE_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
                - name: registration-dir
                  mountPath: /registration
            - name: liveness-probe
              image: quay.io/k8scsi/livenessprobe:v2.0.0
              args:
                - --csi-address=/csi/csi.sock
                - --health-port=9809
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
          volumes:
            - name: kubelet-dir
              hostPath:
                path: /var/data/kubelet
                type: Directory
            - name: plugin-dir
              hostPath:
                path: /var/data/kubelet/plugins/efs.csi.aws.com/
                type: DirectoryOrCreate
            - name: registration-dir
              hostPath:
                path: /var/data/kubelet/plugins_registry/
                type: Directory
            - name: efs-state-dir
              hostPath:
                path: /var/run/efs
                type: DirectoryOrCreate
            - name: efs-utils-config
              hostPath:
                path: /etc/amazon/efs
                type: DirectoryOrCreate
